package life.tannineo.cs7is3.group4;

/**
 * try to determine our own sets
 * all the words with case ignored
 */
public interface CustomWordSet {

    // replace stop words using:
    // https://gist.github.com/sebleier/554280
    String[] customStopWords = {
        "i",
        "me",
        "my",
        "myself",
        "we",
        "our",
        "ours",
        "ourselves",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
        "he",
        "him",
        "his",
        "himself",
        "she",
        "her",
        "hers",
        "herself",
        "it",
        "its",
        "itself",
        "they",
        "them",
        "their",
        "theirs",
        "themselves",
        "what",
        "which",
        "who",
        "whom",
        "this",
        "that",
        "these",
        "those",
        "am",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "having",
        "do",
        "does",
        "did",
        "doing",
        "a",
        "an",
        "the",
        "and",
        "but",
        "if",
        "or",
        "because",
        "as",
        "until",
        "while",
        "of",
        "at",
        "by",
        "for",
        "with",
        "about",
        "against",
        "between",
        "into",
        "through",
        "during",
        "before",
        "after",
        "above",
        "below",
        "to",
        "from",
        "up",
        "down",
        "in",
        "out",
        "on",
        "off",
        "over",
        "under",
        "again",
        "further",
        "then",
        "once",
        "here",
        "there",
        "when",
        "where",
        "why",
        "how",
        "all",
        "any",
        "both",
        "each",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "no",
        "nor",
        "not",
        "only",
        "own",
        "same",
        "so",
        "than",
        "too",
        "very",
        "s",
        "t",
        "can",
        "will",
        "just",
        "don",
        "should",
        "now"
    };

    // A hand pick selection of words not to stem according to the file
    // ./topic
    String[] customWordsNotToStem = {
        "Germany",
        "immigration",
        "genetic",
        "Alzheimer",
        "potassium",
        "magnesium",
        "osteoporosis",
        "disturbance",
        "metabolism",
        "Ireland",
        "radiation",
        "supernova",
        "outburst",
        "comet",
        "interpretation",
        "Parkinson",
        "wildlife",
        "tropical",
        "Lockerbie",
        "Scotland",
        "Schengen",
        "shipwreck",
        "minimill",
        "entrepreneur",
        "Cuba",
        "Golden", "Triangle",
        "Gorges",
        "monoxide",
        "Milosevic",
        "Mirjana",
        "Markovic",
        "Mira",
        "counterfeit",
        "ultraviolet",
        "Legionnaires",
        "Africanized",
        "killer",
        "robotic",
        "motorist",
        "Greek",
        "philosophy",
        "stoicism",
        "Estonia",
        "famine",
        "locomotive",
        "Lyme",
        "sub-Saharan",
        "Saharan",
        "Africa",
        "supercritical",
        "clergy",
        "Stirling",
        "antibiotic",
        "ineffectiveness",
        "King",
        "Hussein",

        // some words not clear, selected by gut feeling
//        "disorders",
//        "issuance",
//        "court",
//        "quilt",
    };

    String[] phrases = {
        "behavioral genetics",
        "Golden Triangle",
        "carbon monoxide",
        "killer bee",
        "Africanized bee",
        "Mirjana Markovic",
        "Stirling engine",
        "King Hussein",
    };
}
